### ISSUE TITLE
Crash on android 7

### ISSUE THREAD

**Issue by anthonybattel** [TrekDev/Xamarin.Android.OpenCV#11]
Sample crash on android 7 on Camera Preview Activity launched. It works on android 6

**Comment by jeremy-ellis-tech** [comment]
Hi Anthony, can you give some more information about the crash. What exactly does it tell you the reason is? Are there any error messages?

**Comment by anthonybattel** [comment]
Hi,

The stacktrace doesn't give me useful information. The crash occur on
enableView function call in camera preview activity.
I can reproduce this crash with an Android emulator on Android 7. It works
on emulator with Android 6.

Thanks

**Comment by jeremy-ellis-tech** [comment]
Hi Anthony,

I believe this is an emulator issue. I've tested on a real phone (Nexus 5X, Android version 7.1.1) and it works fine. Try looking at your emulator settings. I believe some settings can improve performance but cause run-time issues (I had the same problems with my Skobbler bindings). Try turning these off or using a real device.
