### ISSUE TITLE
Max camera video resolution is limited to the surface size

### ISSUE THREAD

**Issue by douglas-carpenedo** [TrekDev/Xamarin.Android.OpenCV#15]
Hi, I'm new to GitHub and developing with OpenCV as well. Sorry for my bad english, isn't my first language. I also do not know if this is the right place for this kind of question. This ins't a issue of this project specifically, but the OpenCV. However, I have not found help elsewhere.

I found a limitation on camera resolution for videos: the video resolution is limited to the free area of the screen. 

For example, on a smarphone with Full HD camera, but 1280x780 screen, OpenCV will not allow to set a video resolution higher than 1280x780. If the application contains menus or something, the available area will be even smaller, consequently the video resolution allowed by the OpenCV will also be smaller.

Analyzing the sources, I think this is caused by the calculateCameraFrameSize(..) method of the CameraBridgeViewBase class

        Int maxAllowedWidth = (mMaxWidth! = MAX_UNSPECIFIED && **mMaxWidth < surfaceWidth**)? MMaxWidth: surfaceWidth;
        Int maxAllowedHeight = (mMaxHeight! = MAX_UNSPECIFIED && **mMaxHeight < surfaceHeight**)? MMaxHeight: surfaceHeight;

I want to do a processing in images larger than screen surface, resizing to display, but storing some frames in high quality.

I changed these lines of code that imposes this limitation, but I do not know how to compile the library (.jar, .a, ..) for its use with Xamarin. Tutorials found led me to error. Can someone help-me?

**Comment by TrekDev** [comment]
Hi @douglas218 No problem. Unfortunately I don't know the answer myself but I'm happy to leave this issue up incase someone does know the answer here.

-TD

**Comment by jeremy-ellis-tech** [comment]
Hi @douglas218. @minhnguyenlinknode asked a similar question about building the library from source. You might be able to get some hints from him. Once you have your `.jar/.a` files you'll simply need to replace the files found in `Xamarin.Android.OpenCV/src/OpenCV.Binding/Jars/`. You can follow the guide [here](https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/) for more help.
