### ISSUE TITLE
Split channels function does not work?

### ISSUE THREAD

**Issue by minhnguyenlinknode** [TrekDev/Xamarin.Android.OpenCV#19]
Hi,

I have tried to use Split function to separate channels of image:

//Load image
Mat rgba = new Mat();
var bitmap = BitmapFactory.DecodeFile(path);
OpenCV.Android.Utils.BitmapToMat(bitmap, rgba);

//Split channels
Mat[] channels = new Mat[4];
Core.Core.Split(rgba, channels);  //channels contains null items !!!

Following is my test image:

![room](https://cloud.githubusercontent.com/assets/9201108/25123691/3107f3f0-2421-11e7-8854-0bb5b5a0ece2.jpg)

**Comment by jeremy-ellis-tech** [comment]
@minhnguyenlinknode Should `Mat[] channels = new Mat[4]` be populated with `new Mat()`s?

**Comment by minhnguyenlinknode** [comment]
I have also tried to poplulate like following, but does not work either. 

channels[0] = new Mat();
channels[1] = new Mat();
channels[2] = new Mat();
channels[3] = new Mat();

I think it is only at my device? I am using SamSung Galaxy Tab Pro.

**Comment by jeremy-ellis-tech** [comment]
@minhnguyenlinknode I think this may only be your device. I can't recreate it on my Nexus 5X.

**Comment by minhnguyenlinknode** [comment]
Thank you very much @TrekDev :)
