### ISSUE TITLE
Stitching is missing

### ISSUE THREAD

**Issue by mariusmuntean** [TrekDev/Xamarin.Android.OpenCV#2]
Hi,

The [Stitcher](http://docs.opencv.org/3.1.0/d2/d8d/classcv_1_1Stitcher.html#gsc.tab=0) seems to be missing even though the [libopencv_stitching.a](https://github.com/TrekDev/Xamarin.Android.OpenCV/blob/master/src/OpenCV.Binding/Jars/arm64-v8a/libopencv_stitching.a) static lib is there.
I'm very much willing to give you feedback on it if you decide to integrate that too(That would make my life a lot easier because I happen to need the Stitcher).

**Comment by jeremy-ellis-tech** [comment]
Hi @mariusmuntean,

The `Stitcher` isn't part of the [Android SDK](http://docs.opencv.org/java/3.1.0/).

If you wish to use the `Stitcher` you'll need to use the `libopencv_stitching.a` library via JNI. An example of how to do this can be seen in the [native face detection tracking in the SDK Demo.](https://github.com/TrekDev/Xamarin.Android.OpenCV/blob/master/src/OpenCV.SDKDemo/FaceDetect/DetectionBasedTracker.cs) or the [mixed processing example](https://github.com/TrekDev/Xamarin.Android.OpenCV/blob/master/src/OpenCV.SDKDemo/MixedProcessing/MixedProcessing.cs#L171)
