### ISSUE TITLE
Can you explain the process of creating the OpenCV.Binding Library?

### ISSUE THREAD

**Issue by ghost** [TrekDev/Xamarin.Android.OpenCV#20]
Can you explain the process of creating the OpenCV.Binding Library?(Please let me know in detail. orz I have no experience with java.) I tried a lot before using this. But I could not find the exact document and it did not succeed.

(like: git glone ... opencv .. cmake -DBUILD_SHARED_LIBS = OFF .. make -j8, etc (I tried to create a jar file in windows10 bash, but this seems to be the wrong approach)

However, I used your code, tested it in the android code of the xamarin cross platform and confirmed the behavior.

I am very curious about how to create this library. It would be nice to use another version of opencv using it.

I would really appreciate it if you could give me a posting or reference document.

Use Google Translate.

**Comment by jeremy-ellis-tech** [comment]
I used [this](http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk)
