### ISSUE TITLE
Java.Lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by CeadeS** [TrekDev/Xamarin.Android.OpenCV#3]
Hey, i get an odd Exception when adding a Line at Line 47 of ColorBlobDetectionActivity.cs :`Mat foo = new Mat()` at other places there is no Problem with the constructor, except here. i do not get it.

`04-22 15:05:19.774 I/ColorBlobDetection( 5060): Instantiated new OpenCV.SDKDemo.ColorBlobDetection.ColorBlobDetectionActivity
04-22 15:05:19.789 W/dalvikvm( 5060): No implementation found for native Lorg/opencv/core/Mat;.n_Mat:(III)J
Unhandled Exception:

Java.Lang.UnsatisfiedLinkError: Native method not found: org.opencv.core.Mat.n_Mat:(III)J`

**Comment by jeremy-ellis-tech** [comment]
Hi @CeadeS,

Is this running the SDK demo with no other changes, or in your own program?

**Comment by jeremy-ellis-tech** [comment]
I quick google led me to [this stackoverflow answer](https://stackoverflow.com/questions/24566127/jni-java-lang-unsatisfiedlinkerror-native-method-not-found)

I'm assuming it isn't finding the `libopencv_core.a` library. It could be that the correct `.a` file isn't included in the generated `.dll`, maybe due to the build configuration not matching your phone's architecture (`arm`, `x86`, etc...)

**Comment by CeadeS** [comment]
Okay, thanks for that, ill try as soon as i have my computer back ;)
This exception is thrown in the SDK Demo after i tried similar code at my project. I wanted to test if i altered something that made this happen. The Code runs on 2 different phones with exactly the same behaviour. 
If it does not find the core library object file, the other code would throw the same exception i guess. I try next what happenes when i use other functions and classes inside the core object. Everything else seems to build and rebuild just fine.

**Comment by CeadeS** [comment]
okay, sry my fault... never use library before loading it

**Comment by jeremy-ellis-tech** [comment]
No problem. Thanks for letting me know it's sorted.
