### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by JelleDamen** [TrekDev/Xamarin.Android.OpenCV#5]
Any plans for a NuGet Package? I would love to help

**Comment by jeremy-ellis-tech** [comment]
Yep. I've been planning on a nuget package for a while, but was just waiting until it was stable enough and I'd caught most of the bugs. Seems ok as it is. I'll get one out by the weekend.

**Comment by JelleDamen** [comment]
Thanks and great work btw!

**Comment by jeremy-ellis-tech** [comment]
@JelleDamen Bad news. I tried releasing a nuget package last night but ran into a size issue. I think the maximum size for a nuget package might be 30MB. I tried uploading the `Release | AnyCPU` package both through the `nuget.exe` client and the web interface and both failed with timeout errors.
