### ISSUE TITLE
VideoWriter

### ISSUE THREAD

**Issue by shadow111** [TrekDev/Xamarin.Android.OpenCV#7]
does this version of opencv support video writer or video reader?

**Comment by jeremy-ellis-tech** [comment]
Yes, any classes you find in the [3.1.0 java documentation](http://docs.opencv.org/java/3.1.0/) will have bindings in this C# library. It looks like the VideoWriter class is exposed in the Java library, but the VideoReader isn't. However, you may be able to use VideoReader function with PInvoke, there are examples of doing this in the [SDKDemo project](https://github.com/TrekDev/Xamarin.Android.OpenCV/blob/master/src/OpenCV.SDKDemo/MixedProcessing/MixedProcessing.cs#L171)

**Comment by shadow111** [comment]
Please can you explain to me what lib (.so file) should i add to my xamarin project , s i can get my project working. my project is to get a specific frame from a video then modify it, then write a new video with the modyfied frame. i have add the opencv.dll to my project References.
Thank you

**Comment by jeremy-ellis-tech** [comment]
The .so file will be one of the libraries under [OpenCV.Binding/Jars](https://github.com/TrekDev/Xamarin.Android.OpenCV/tree/master/src/OpenCV.Binding/Jars). I haven't used the video functions in OpenCV so you'll have to read the OpenCV documentation to find out.

**Comment by shadow111** [comment]
but here is one that use video libopencv_videoio.a ??
