### ISSUE TITLE
Classes from OpenCV.Android namespace not available

### ISSUE THREAD

**Issue by Bennik2000** [TrekDev/Xamarin.Android.OpenCV#8]
Hello TrekDev,
thanks for this nice library! Unfortunately I cannot get the sample project running. The classes `CameraBridgeViewBase`, `BaseLoaderCallback`, `OpenCVLoader` are not available even in the object browser so I cannot compile the OpenCV.SDKDemo project (OpenCV.Binding works fine).

It would be great if you helped me!

Regards,
Bennik2000

**Comment by jeremy-ellis-tech** [comment]
Hi Bennik,

Are any namespaces/classes visible in the ObjectBrowser? What JDK version are  you using? I've successfully compiled from a clean clone using jdk1.8.0_102 (32 bit).

Can you also make sure everything is up to date? (via Xamarin and the Android SDK manager)

I've found in the past what you're describing may happen with the Xamarin Visual Studio extension. Restarting Visual Studio then cleaning and rebuilding the solution may fix it.

-TD

**Comment by Bennik2000** [comment]
Hello TrekDev,

Well.. now the build process works. 
The problem was an outdated JDK version (jdk1.7.0_55 / 32Bit). I installed a new version a month ago but forgot to update the path in the Xamarin settings.

Then I had to clean the visual studio cache and restart VS.

Thank you for the quick response!

Bennik2000
