### ISSUE TITLE
building droid project using Multi-Dex flag issues.

### ISSUE THREAD

**Issue by michaelgobbers** [TrekDev/Xamarin.Android.OpenCV#9]
I'm currently facing a problem where I'm hitting the 512k method limit in my project. Android SDK tooling provides an option to enable multi-dex builds which goes arround this limit. But this conflicts with the openCV library. The build currently fails on the fact that the "opencv library - 3.1.0.jar" contains spaces.

I tried opening up the zip remove the spaces, zip it again and rebuild but now the opencv library isn't building anymore. I get the following error:

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Bindings.targets: error : At least one Java library is required for binding, this must be either 'EmbeddedJar', 'InputJar' (for jar), 'LibraryProjectZip' (for aar or zip) or 'LibraryProjectProperties' (project.properties) build action.`

This happens while the zip does have the LibraryProjectZip Build action.

**Comment by jeremy-ellis-tech** [comment]
Hi Michael,

I've tried to recreate your issue by simply enabling multi-dex support in the `OpenCV.SDKDemo` project without changing the library project zip file and then by unzipping, removing spaces from the jar's file name and rezipping; both methods have worked.

Sorry, but I think this is an issue with your App project or build tools. Since enabling MultiDex is done in your App project, not in this binding library it's very difficult to diagnose. The best help I can offer is suggesting you make sure your built-tools (Xamarin.Android, JDK, SDKs, etc.) are up to date. For reference I'm using jdk1.8.0_102 and XamarinVS 4.2.0.719.

-TD

**Comment by michaelgobbers** [comment]
I tried building the demo with Xamarin studio with multi dex support enabled. It fails with the same issue.

I tried to run it with Visual Studio and indeed there is seems to work. I'm going to raise an issue on the Xamarin forums as this seems to be an issue with the toolchain for Xamarin Studio.

**Comment by michaelgobbers** [comment]
I've posted this issue on xamarin forums but at the moment I'm not having a lot of luck over there. 
Anyway, for the moment I probably will have to work around the issue by removing the spaces from the .jar library. I tried doing this in the demo project but I'm still getting the issue as it described in my first post. (Also in Visual Studio)

Did you do anything special to make this work? It seems that it isn't recognising the zip as I'm getting errors that I don't have a java library included...

**Comment by jeremy-ellis-tech** [comment]
Nope nothing special at all. What jdk/sdk versions are you using?

**Comment by michaelgobbers** [comment]
I have the latest platform tools installed as well as jdk 1.8.0_101.
Would it be possible for you to maybe send me the zip?

**Comment by jeremy-ellis-tech** [comment]
A zip of what exactly? I used jdk1.8.0_102 successfully, I recommend updating to that and seeing if you have more success.

**Comment by michaelgobbers** [comment]
The zip that contains the .jar file without spaces. Anyway I'll try to give the jdk update a go.

**Comment by jeremy-ellis-tech** [comment]
It's just the zip as included in the Bindings project, nothing special and since it worked without me having to change the file name I don't think me sending it to you is worthwhile. I used 7zip to extract & rezip the file.

**Comment by michaelgobbers** [comment]
Oh so you didn't change the filename of the .jar file inside the zip file? Thats the file that breaks the multidex support on xamarin studio. (edit: and for visual studio)

**Comment by jeremy-ellis-tech** [comment]
Yes I have. I have tried two things since you raised this issue:
1. Just enabling multidex in the SDKDemo project _without_ changing anything else. It worked fine.
2. Enabling multidex in the SDKDemo project _and_ removed the spaces in the Jar's filename in the opencv-3.1.0.zip of the Binding project. That also worked.

**Comment by michaelgobbers** [comment]
So to be clear I'm indeed talking about the second method. However, that is not working for me. That's why I was asking about the zip as that is the only thing that changed from the repository code. If I had it, I could verify that it is indeed a problem with my machine config.

**Comment by jeremy-ellis-tech** [comment]
All I did was unzip the file from the repo using 7zip, change Jar file name, rezip it using 7zip. I don't have access to a windows machine at the moment. Just repeat the steps above.

**Comment by michaelgobbers** [comment]
Wow... It did seem to work if I just go in to the zip with 7zip and change the name. Why it doesn't work with the built in windows 10 archiving tool is a mystery to me... 

Anyway, thank you for your help!

I could make a pull request with the updated zip if you want? This will prevent people to run in to the same issue as I did with the multidex support.
